const express=require('express'),multer=require('multer'),cors=require('cors');
const {spawn}=require('child_process');const fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');
const app=express();app.use(cors({origin:true}));
const upload=multer({dest:path.join(os.tmpdir(),'viral-studio-pc'),limits:{fileSize:500*1024*1024}});
app.get('/',(_q,r)=>r.json({ok:true,service:'Viral Studio Render PC',version:'1.0'}));
app.get('/health',(_q,r)=>r.json({ok:true,engine:'pc',version:'1.0'}));
function run(args){return new Promise((ok,no)=>{const p=spawn('ffmpeg',args,{stdio:['ignore','ignore','pipe']});let e='';p.stderr.on('data',d=>e+=d);p.on('error',no);p.on('close',c=>c===0?ok():no(new Error(e||'ffmpeg '+c)))})}
app.post('/render',upload.array('clips',20),async(req,res)=>{const files=req.files||[];if(!files.length)return res.status(400).json({error:'Envie clips'});const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vs-'));const list=path.join(dir,'list.txt'),out=path.join(dir,'out.mp4');const cleanup=()=>{try{files.forEach(f=>fs.rmSync(f.path,{force:true}));fs.rmSync(dir,{recursive:true,force:true})}catch{}};try{fs.writeFileSync(list,files.map(f=>`file '${f.path.replaceAll("'","'\\''")}'`).join('\n'));try{await run(['-y','-hide_banner','-loglevel','error','-f','concat','-safe','0','-i',list,'-map','0:v:0?','-map','0:a:0?','-c','copy','-movflags','+faststart',out])}catch(_){const norm=[];for(let i=0;i<files.length;i++){const n=path.join(dir,`n${i}.mp4`);await run(['-y','-hide_banner','-loglevel','error','-i',files[i].path,'-c:v','libx264','-preset','ultrafast','-crf','24','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-ar','44100',n]);norm.push(n)}fs.writeFileSync(list,norm.map(f=>`file '${f}'`).join('\n'));await run(['-y','-hide_banner','-loglevel','error','-f','concat','-safe','0','-i',list,'-c','copy','-movflags','+faststart',out])}res.type('video/mp4');res.set('Content-Disposition','attachment; filename="viral-studio.mp4"');const st=fs.statSync(out);res.set('Content-Length',String(st.size));const rs=fs.createReadStream(out);rs.pipe(res);rs.on('close',cleanup)}catch(e){cleanup();res.status(500).json({error:'Falha ao renderizar',detail:String(e.message||e).slice(-1500)})}});
app.listen(10000,'0.0.0.0',()=>console.log('Viral Studio Render PC pronto na porta 10000'));
